<?php require_once  './app/views/layout/header.php'; ?>
<div class="d-flex justify-content-center align-content-center">
    <div>
        <div class="text-center" style="letter-spacing: 4px; font-family: 'Times New Roman', Times, serif;">
            <h3>FERRETERIA LA FERROVIARIA</h3>
           
        </div>
    <div >
        <img style="width: 650px; height: 500px;" src="<?=BASE_URL?>/resources/img/icon.png" alt="LA FERROVIARIA">
    </div>

    </div>
   

</div>
<?php require_once  './app/views/layout/footer.php'; ?>